CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE users(id UUID PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, username TEXT UNIQUE NOT NULL, full_name TEXT, role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','admin')), is_verified BOOLEAN DEFAULT false, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE categories(id UUID PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL);
CREATE TABLE brands(id UUID PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL);
CREATE TABLE products(id UUID PRIMARY KEY, seller_id UUID REFERENCES users(id), category_id UUID REFERENCES categories(id), brand_id UUID REFERENCES brands(id), title TEXT NOT NULL, description TEXT, price BIGINT NOT NULL, condition TEXT CHECK(condition IN ('new','like_new','good','fair')), size TEXT, color TEXT, material TEXT, location TEXT, status TEXT DEFAULT 'ACTIVE' CHECK(status IN ('DRAFT','ACTIVE','RESERVED','SOLD','ARCHIVED')), views INT DEFAULT 0, search_vector tsvector, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX idx_products_search ON products USING GIN(search_vector);
CREATE INDEX idx_products_status ON products(status);
CREATE TABLE product_images(id UUID PRIMARY KEY, product_id UUID REFERENCES products(id) ON DELETE CASCADE, url TEXT NOT NULL);
CREATE TABLE carts(id UUID PRIMARY KEY, user_id UUID UNIQUE REFERENCES users(id));
CREATE TABLE cart_items(id UUID PRIMARY KEY, cart_id UUID REFERENCES carts(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id), quantity INT DEFAULT 1, UNIQUE(cart_id,product_id));
CREATE TABLE orders(id UUID PRIMARY KEY, buyer_id UUID REFERENCES users(id), status TEXT CHECK(status IN ('PENDING_PAYMENT','PAID','PROCESSING','SHIPPED','DELIVERED','COMPLETED','CANCELLED','REFUND_REQUESTED','REFUNDED')), total BIGINT, shipping_address TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE order_items(id UUID PRIMARY KEY, order_id UUID REFERENCES orders(id) ON DELETE CASCADE, product_id UUID REFERENCES products(id), price BIGINT);
CREATE TABLE wishlists(id UUID PRIMARY KEY, user_id UUID REFERENCES users(id), product_id UUID REFERENCES products(id), UNIQUE(user_id,product_id));
CREATE TABLE reviews(id UUID PRIMARY KEY, product_id UUID REFERENCES products(id), user_id UUID REFERENCES users(id), rating INT CHECK(rating BETWEEN 1 AND 5), comment TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE follows(follower_id UUID REFERENCES users(id), following_id UUID REFERENCES users(id), PRIMARY KEY(follower_id,following_id));
CREATE TABLE chat_rooms(id UUID PRIMARY KEY, buyer_id UUID REFERENCES users(id), seller_id UUID REFERENCES users(id), product_id UUID REFERENCES products(id));
CREATE TABLE chat_messages(id UUID PRIMARY KEY, room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE, sender_id UUID REFERENCES users(id), content TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE notifications(id UUID PRIMARY KEY, user_id UUID REFERENCES users(id), title TEXT, body TEXT, is_read BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE refresh_tokens(id UUID PRIMARY KEY, user_id UUID REFERENCES users(id), token TEXT UNIQUE, expires_at TIMESTAMPTZ, revoked BOOLEAN DEFAULT false);
CREATE TABLE reports(id UUID PRIMARY KEY, reporter_id UUID REFERENCES users(id), target_id UUID, reason TEXT, created_at TIMESTAMPTZ DEFAULT now());
